### ISSUE TITLE
Unsafe usage of localStorage

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-events#10]
https://github.com/mapbox/mapbox-events/blob/master/index.js#L43-L53

This code will fail in browsers configured to disallow localStorage: these browsers will pass the check for localStorage being present, but throw when you interact with localStorage. The set/get calls should be included in the try/catch block.

**Comment by 1ec5** [comment]
Specifically, this affects Safari (both iOS and OS X) in Private Browsing mode.

**Comment by camilleanne** [comment]
cc @willwhite

**Comment by tmcw** [comment]
PR: #11
